services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  sender:
    build:
      context: ./sender
      dockerfile: Dockerfile
    container_name: sender
    depends_on:
      mosquitto:
        condition: service_started
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    container_name: receiver
    depends_on:
      mosquitto:
        condition: service_started
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  middleware1:
    build:
      context: ./middleware1
      dockerfile: Dockerfile
    container_name: middleware1
    depends_on:
      mosquitto:
        condition: service_started
      receiver:
        condition: service_started
    environment:
      - MIDDLEWARE_TYPE=circuit_breaker

  middleware2:
    build:
      context: ./middleware2
      dockerfile: Dockerfile
    container_name: middleware2        # ✅ fixar nome para não permitir múltiplas réplicas
    depends_on:
      mosquitto:
        condition: service_started
      receiver:
        condition: service_started
    environment:
      - MIDDLEWARE_TYPE=replication
    # ❌ REMOVER este bloco se quiser apenas 1 instância:
    # deploy:
    #   replicas: 3

  middleware3:
    build:
      context: ./middleware3
      dockerfile: Dockerfile
    container_name: middleware3
    depends_on:
      mosquitto:
        condition: service_started
      receiver:
        condition: service_started
    environment:
      - MIDDLEWARE_TYPE=pipeline
